[env:esp32dev]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bblanchon/ArduinoJson@^6.21.3

build_flags =
    -DBOARD_HAS_PSRAM=0
    -DARDUINO_ESP32_DEV
