[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

monitor_speed = 115200
monitor_filters = send_on_enter
monitor_echo = yes

lib_deps =
    bblanchon/ArduinoJson@^6.21.3

build_flags =
    -DPICO_STACK_SIZE=4096
