[platformio]
boards_dir = boards

[env:gd32f205]
platform = https://github.com/CommunityGD32Cores/platform-gd32.git
platform_packages = framework-spl-gd32@https://github.com/bigtreetech/gd32-pio-spl-package
framework = spl
board = GD32F205VC_0x3000
board_build.ldscript = ldscripts/gd32f20xxC_0x3000_iap.ld
build_flags =
    -DGD32F2XX
    -DHXTAL_VALUE=8000000ul
    -DVECT_TAB_FLASH=0x08003000
    -DUSE_STDPERIPH_DRIVER
    -Iinclude
upload_protocol = cmsis-dap
