[env:gd32f205]
platform = ststm32
board = gd32f205vct6
framework = arduino

monitor_speed = 115200
upload_protocol = stlink

lib_deps =
    lvgl/lvgl@^8.3.0
    greiman/SdFat@^2.2.0

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DSTM32F2xx
    -DSTM32F205xx
    -DARDUINO_GENERIC_F205VCTX
    -I src
